### ISSUE TITLE
Error at the first use

### ISSUE THREAD

**Issue by darlopvil** [nosiegel/ADOR#2]
Hi, hope everything's ok.

So this is what i get when using the addon in a random maze. Maybe is because of the Anki versions. In the addon page it says 1.2.0, but i'm currently using the last version (2.1.61).

-----------------------------------------------------------
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-04-13 19:36:00

Caught exception:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1776268610\__init__.py", line 56, in accept
    self.reschedule(self.deck_id, off, into, algo)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1776268610\__init__.py", line 84, in reschedule
    highestDue: int = cards.__getitem__(0).due
IndexError: list index out of range

**Comment by nosiegel** [comment]
Thank you for sharing this with me. I will take a look. Would you be able
to share your collection with scheduling information?

**Comment by darlopvil** [comment]
I'm sorry, but I don't think I understood you. You mean to share a maze? my whole Anki collection?

I just created a random test-like maze to use the addon:

![imagen](https://user-images.githubusercontent.com/60988792/232047985-3df940ff-b5a2-4808-9e6e-c98baf73b093.png)

**Comment by nosiegel** [comment]
I’ll submit a patch for this in a few days. You have no cards due so there
is nothing to reschedule. Try it again when you have some due (green) cards

**Comment by darlopvil** [comment]
Oh, ok then. Tried it on a maze with new cards (blue), review cards (orange) and due cards (green).
With this config:
![imagen](https://user-images.githubusercontent.com/60988792/232066765-2293be1f-0899-40b8-b26c-2ef366d1a468.png)

This is what I got:
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-04-13 19:36:00

Caught exception:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1776268610\__init__.py", line 56, in accept
    self.reschedule(self.deck_id, off, into, algo)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1776268610\__init__.py", line 84, in reschedule
    highestDue: int = cards.__getitem__(0).due
IndexError: list index out of range


P.S.: idk if this can be of any help, but i cannot change the "deafult" value in the "Algorithm" field

**Comment by nosiegel** [comment]
Can I see the picture of that maze as well

**Comment by darlopvil** [comment]
This is what you need?

![imagen](https://user-images.githubusercontent.com/60988792/232149052-7cbe645e-1184-4eb8-bdd2-07c0dd05286d.png)

**Comment by nosiegel** [comment]
Yes that’s it. It also looks like sesion A has no due cards. Did it have
any before you used the add on? If not, the add on needs to be used on a
deck with due cards.

**Comment by darlopvil** [comment]
Well, it's kind of weird what happened. Indeed, "Sesion A" did have a lot of green cards, so i used the addon in there. Then, the error message from the post above prompt and all the green cards disappeared. But when i tried to do the same with the rest of the mazes (Sesion B, Sesion C, etc) it only gave me the error message.

Now it behaves completely different. Sometimes it works, sometimes not. The same with the error message, it prompts or not when you use the addon. I've made a video about the behavior of the addon. I've to click on “synchronize” to see results. But it doesn't work smoothly tbh.




https://user-images.githubusercontent.com/60988792/232219855-d1861032-20c4-4334-8e15-6cb1bde3d589.mp4
